[pytest]
pythonpath =
    aikea/scripts
    aikea-build-units/scripts
    aikea-build-drawers/scripts
    aikea-build-doors/scripts
    aikea-add-lighting/scripts
    aikea-review-unit/scripts
    aikea-source-hardware-cad/scripts
    tests
